title: Single Node Hadoop Installation on Ubuntu 14.04 Amazon EC2 Instance
description: by Ashish Tamrakar (UNLV)
google_analytics: UA-74861100-1
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
